### ISSUE TITLE
Symlinks are wrongly tested

### ISSUE THREAD

**Issue by YetiCGN** [TYPO3/Surf#630] opened 2022-11-15 14:45 UTC
## Expected Behavior
Symlinks correctly set as before in Surf 3.3.4.

## Actual Behavior
Error in CreateSymlinksTask: Insufficient permissions to create directory `../../../../shared`

I think the problem stems from the fact that the symlinks need to go up a few more directories, the deeper they are set in subdirectories but the test introduced with https://github.com/TYPO3/Surf/compare/8a29bb..079bd0 always checks from the base directory `{releasePath}`.

## Steps to Reproduce the Problem

  1. Use symlinks with relative paths like this:

    $application = new \TYPO3\Surf\Application\TYPO3\CMS();
    [...]
    $application->setSymlinks([
        '.env' => '../../shared/.env',
        'config/sites' => '../../../shared/sites',
        'public/medien' => '../../../shared/Data/medien',
        'public/typo3conf/LocalConfiguration.php' => '../../../../shared/Configuration/LocalConfiguration.php',
        'public/typo3conf/image_autoresize.config.php' => '../../../../shared/Configuration/image_autoresize.config.php',
        'public/typo3temp/var/logs' => '../../../shared/Data/Logs',
        'public/uploads' => '../../../shared/Data/uploads',
        'public/robots.txt' => '../../../shared/robots.txt',
      ]);

## Specifications

  - Surf Version: 3.3.5 (regression from 3.3.4)
  - Application: TYPO3 10.4.32
  - PHP Version: 7.4.32
  - Platform: Ubuntu Linux 20.04 (through WSL 1)
  - Environment (CI): irrelevant
  - Deployment configuration: TYPO3\Surf\Application\TYPO3\CMS

**Comment by tbsschmdt** [comment] 2022-12-21 12:46
I can confirm this. Testing and creation of symlinks only works for symlinks in the root directory of a release. Depending on the users permissions symlinks in subdirectories lead to the mentioned error message or to additionally created directories one, two or more levels above the root directoy of the deployment.

**Comment by PRGfx** [comment] 2023-04-05 08:40
Looking at the code in question I'm wondering if it actually does, what it should do.
https://github.com/TYPO3/Surf/blob/079bd0ef221bea2febfdb7ac26a403e5078d5047/src/Task/Generic/CreateSymlinksTask.php#L56-L59
I would think the link target (the `$sourcePath`) should exist (or we assume it will exist at some point at least), so we would rather check for the **`dirname`** of the `$linkPath` - the point is about making sure the symlink can be created, or am I misunderstanding?

**Comment by YetiCGN** [comment] 2023-04-05 14:46
@sabbelasichon You know what? I've solved this for us with a simple [Composer patch](https://packagist.org/packages/cweagans/composer-patches). No hurry.

**Comment by tbsschmdt** [comment] 2023-04-12 11:29
I suggest to reopen this issue. Introducing an option to disable directory creation doesn't make this feature less flawed. The creation of target directories works only for symlinks in the root directory of a release. For symlinks in subdirectories it is still broken.  Depending on the users permissions symlinks in subdirectories lead to an error message or to additionally created directories one, two or more levels above the root directoy of the deployment. The latter results in broken symlinks because target directories are created in the wrong place.

**Comment by simonschaufi** [comment] 2023-10-27 21:33
Fixed with https://github.com/TYPO3/Surf/commit/00290c6015440afb6d268135c0e41443f398125c. Sorry, I didn't link this issue with the commit.

**Closed by simonschaufi** 2023-10-27 21:33 UTC
Labels: bug
